# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/8191588/FPGA_mag2.1_lab1/BD/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
# IP: The module: 'system_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/8191588/FPGA_mag2.1_lab1/BD/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/8191588/FPGA_mag2.1_lab1/BD/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/8191588/FPGA_mag2.1_lab1/BD/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/8191588/FPGA_mag2.1_lab1/BD/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
# IP: The module: 'system_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/8191588/FPGA_mag2.1_lab1/BD/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/8191588/FPGA_mag2.1_lab1/BD/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/8191588/FPGA_mag2.1_lab1/BD/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
